# Generated by Django 5.1.1 on 2024-10-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0003_alter_reptile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reptile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重 (g)'),
        ),
    ]
