# Generated by Django 5.1.1 on 2024-10-22 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0004_reptile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('reptile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_logs', to='reptile.reptile')),
            ],
        ),
    ]
