# Generated by Django 5.1.1 on 2024-10-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0005_alter_feedingrecord_notes_feedinglog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='notes',
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='food_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='memo',
            field=models.TextField(blank=True),
        ),
    ]
