# Generated by Django 5.1.1 on 2024-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0006_remove_feedingrecord_notes_feedingrecord_food_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
