# Generated by Django 5.1.1 on 2024-10-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0007_feedingrecord_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='memo',
        ),
    ]
