# Generated by Django 5.1.1 on 2024-10-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0008_remove_feedingrecord_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
