# Generated by Django 5.1.1 on 2024-10-22 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0009_feedingrecord_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='feedingrecord',
            name='memo',
        ),
    ]
