# Generated by Django 5.1.1 on 2024-10-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0010_remove_feedingrecord_food_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='food_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
