# Generated by Django 5.1.1 on 2024-10-23 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0011_feedingrecord_food_type_feedingrecord_memo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='date',
        ),
        migrations.RemoveField(
            model_name='feedingrecord',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='feedingrecord',
            name='weight',
        ),
    ]
