# Generated by Django 5.1.1 on 2024-10-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0012_remove_feedingrecord_date_remove_feedingrecord_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
