# Generated by Django 5.1.1 on 2024-10-23 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0013_feedingrecord_date_feedingrecord_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight', models.FloatField()),
                ('reptile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptile.reptile')),
            ],
        ),
    ]
