# Generated by Django 5.1.1 on 2024-10-24 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0014_weightrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='weight',
        ),
    ]
