# Generated by Django 5.1.1 on 2024-10-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0015_remove_feedingrecord_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='notes',
        ),
    ]
