# Generated by Django 5.1.1 on 2024-10-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0016_remove_feedingrecord_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
