# Generated by Django 5.1.1 on 2024-10-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0019_remove_feedingrecord_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='体重 (g)'),
        ),
    ]
