# Generated by Django 5.1.1 on 2024-10-28 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0020_feedingrecord_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feeding_images/'),
        ),
    ]
