# Generated by Django 5.1.1 on 2024-10-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0021_feedingrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
