# Generated by Django 5.1.1 on 2024-10-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0022_alter_feedingrecord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedingrecord',
            name='image',
        ),
    ]
