# Generated by Django 5.1.1 on 2024-10-29 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0023_remove_feedingrecord_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedinglog',
            name='description',
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='food_type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='feedinglog',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='care_items',
            field=models.CharField(blank=True, choices=[('cleaning', '掃除'), ('bathing', '温浴'), ('handling', 'ハンドリング'), ('water_change', '水替え')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='health_status',
            field=models.CharField(blank=True, choices=[('very_good', 'かなり良好'), ('good', '良好'), ('normal', '普通'), ('slightly_bad', '少し悪い'), ('very_bad', 'かなり悪い')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='feeding_images/'),
        ),
        migrations.AlterField(
            model_name='feedinglog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedinglog',
            name='reptile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reptile.reptile'),
        ),
    ]
