# Generated by Django 5.1.1 on 2024-10-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0024_remove_feedinglog_description_feedinglog_food_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
