# Generated by Django 5.1.1 on 2024-10-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0025_alter_feedingrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
