# Generated by Django 5.1.1 on 2024-10-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0026_alter_feedingrecord_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='care_items',
            field=models.CharField(choices=[('cleaning', '掃除'), ('bathing', '温浴'), ('handling', 'ハンドリング'), ('water_change', '水替え')], default='cleaning', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
