# Generated by Django 5.1.1 on 2024-10-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0027_alter_feedingrecord_care_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='care_items',
            field=models.CharField(blank=True, choices=[('cleaning', '掃除'), ('bathing', '温浴'), ('handling', 'ハンドリング'), ('water_change', '水替え')], max_length=20, null=True),
        ),
    ]
