# Generated by Django 5.1.1 on 2024-10-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0028_alter_feedingrecord_care_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='care_items',
            field=models.CharField(choices=[('掃除', '掃除'), ('温浴', '温浴'), ('ハンドリング', 'ハンドリング'), ('水替え', '水替え')], default='選択なし', max_length=20),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='health_status',
            field=models.CharField(blank=True, choices=[('かなり良好', 'かなり良好'), ('良好', '良好'), ('普通', '普通'), ('少し悪い', '少し悪い'), ('かなり悪い', 'かなり悪い')], max_length=20, null=True),
        ),
    ]
