# Generated by Django 5.1.1 on 2024-10-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0029_alter_feedingrecord_care_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='care_items',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
