# Generated by Django 5.1.1 on 2024-10-30 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0030_alter_feedingrecord_care_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedingrecord',
            name='feces_and_urine',
            field=models.CharField(blank=True, choices=[('good', 'いい'), ('bad', 'わるい')], max_length=10),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='shedding',
            field=models.CharField(blank=True, choices=[('cloudy', '白濁'), ('molting', '脱皮')], max_length=10),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='health_status',
            field=models.CharField(blank=True, choices=[('very_good', 'かなり良好'), ('good', '良好'), ('normal', '普通'), ('slightly_bad', '少し悪い'), ('very_bad', 'かなり悪い')], max_length=20, null=True),
        ),
    ]
