# Generated by Django 5.1.1 on 2024-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0031_feedingrecord_feces_and_urine_feedingrecord_shedding_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='shedding',
            field=models.CharField(blank=True, choices=[('白濁', '白濁'), ('脱皮', '脱皮')], max_length=10),
        ),
    ]
