# Generated by Django 5.1.1 on 2024-11-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0032_alter_feedingrecord_shedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='shedding',
            field=models.CharField(blank=True, choices=[('cloudy', '白濁'), ('molting', '脱皮')], max_length=10),
        ),
    ]
