# Generated by Django 5.1.1 on 2024-11-12 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reptile', '0033_alter_feedingrecord_shedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedingrecord',
            name='feces_and_urine',
            field=models.CharField(blank=True, choices=[('いい', 'いい'), ('わるい', 'わるい')], max_length=10),
        ),
        migrations.AlterField(
            model_name='feedingrecord',
            name='shedding',
            field=models.CharField(blank=True, choices=[('白濁', '白濁'), ('脱皮', '脱皮')], max_length=10),
        ),
    ]
